// ============================================================
// Media Database — Manga, Books, TV Shows, Movies
// ============================================================

const DATABASE = [

  // ========================  MANGA  ========================
  { title: "Naruto", category: "manga", genres: ["action", "adventure", "shounen", "martial arts"], year: 1999, description: "A young ninja seeks recognition and dreams of becoming the strongest leader." },
  { title: "One Piece", category: "manga", genres: ["action", "adventure", "comedy", "shounen"], year: 1997, description: "A pirate crew sails the Grand Line searching for the ultimate treasure." },
  { title: "Attack on Titan", category: "manga", genres: ["action", "dark fantasy", "drama", "mystery"], year: 2009, description: "Humanity fights for survival against giant humanoid creatures." },
  { title: "Death Note", category: "manga", genres: ["thriller", "psychological", "mystery", "supernatural"], year: 2003, description: "A student finds a notebook that kills anyone whose name is written in it." },
  { title: "Demon Slayer", category: "manga", genres: ["action", "adventure", "dark fantasy", "shounen"], year: 2016, description: "A boy becomes a demon slayer to save his sister." },
  { title: "My Hero Academia", category: "manga", genres: ["action", "superhero", "comedy", "shounen"], year: 2014, description: "A powerless boy inherits a superpower and enrolls in a hero academy." },
  { title: "Jujutsu Kaisen", category: "manga", genres: ["action", "dark fantasy", "supernatural", "shounen"], year: 2018, description: "A student swallows a cursed object and enters the world of sorcerers." },
  { title: "Fullmetal Alchemist", category: "manga", genres: ["action", "adventure", "fantasy", "drama"], year: 2001, description: "Two brothers use alchemy to search for the Philosopher's Stone." },
  { title: "Dragon Ball", category: "manga", genres: ["action", "adventure", "comedy", "martial arts", "shounen"], year: 1984, description: "A boy with a monkey tail trains to become the strongest fighter." },
  { title: "One Punch Man", category: "manga", genres: ["action", "comedy", "superhero", "satire"], year: 2009, description: "A hero so powerful he defeats every enemy with a single punch." },
  { title: "Chainsaw Man", category: "manga", genres: ["action", "dark fantasy", "horror", "shounen"], year: 2018, description: "A boy merges with a chainsaw devil and becomes a devil hunter." },
  { title: "Spy x Family", category: "manga", genres: ["action", "comedy", "slice of life", "shounen"], year: 2019, description: "A spy, assassin, and telepath form a fake family." },
  { title: "Berserk", category: "manga", genres: ["action", "dark fantasy", "horror", "drama"], year: 1989, description: "A lone warrior battles demons in a brutal medieval world." },
  { title: "Tokyo Ghoul", category: "manga", genres: ["action", "dark fantasy", "horror", "psychological"], year: 2011, description: "A college student becomes half-ghoul after a deadly encounter." },
  { title: "Hunter x Hunter", category: "manga", genres: ["action", "adventure", "fantasy", "shounen"], year: 1998, description: "A boy becomes a Hunter to find his missing father." },
  { title: "Bleach", category: "manga", genres: ["action", "adventure", "supernatural", "shounen"], year: 2001, description: "A teenager gains soul reaper powers and protects the living world." },
  { title: "Vinland Saga", category: "manga", genres: ["action", "adventure", "drama", "historical"], year: 2005, description: "A Viking warrior seeks revenge in a brutal medieval world." },
  { title: "Sailor Moon", category: "manga", genres: ["fantasy", "romance", "shoujo", "magical girl"], year: 1991, description: "A schoolgirl transforms into a magical warrior to protect Earth." },
  { title: "Slam Dunk", category: "manga", genres: ["comedy", "sports", "drama", "shounen"], year: 1990, description: "A delinquent joins a basketball team to impress a girl." },
  { title: "Haikyuu!!", category: "manga", genres: ["sports", "comedy", "drama", "shounen"], year: 2012, description: "A short volleyball player aims to become the best." },
  { title: "Blue Lock", category: "manga", genres: ["sports", "drama", "psychological", "shounen"], year: 2018, description: "300 strikers compete in a ruthless program to create Japan's best." },
  { title: "Vagabond", category: "manga", genres: ["action", "adventure", "drama", "historical", "martial arts"], year: 1998, description: "The story of legendary swordsman Miyamoto Musashi." },
  { title: "Monster", category: "manga", genres: ["drama", "mystery", "psychological", "thriller"], year: 1994, description: "A doctor hunts a former patient who became a serial killer." },
  { title: "20th Century Boys", category: "manga", genres: ["mystery", "sci-fi", "thriller", "drama"], year: 1999, description: "A group of friends must stop a cult leader's apocalyptic plans." },
  { title: "Goodnight Punpun", category: "manga", genres: ["drama", "psychological", "slice of life", "coming-of-age"], year: 2007, description: "A boy's dark journey through adolescence and adulthood." },
  { title: "Mob Psycho 100", category: "manga", genres: ["action", "comedy", "supernatural", "slice of life"], year: 2012, description: "A powerful psychic kid just wants a normal life." },
  { title: "Dandadan", category: "manga", genres: ["action", "comedy", "supernatural", "sci-fi", "romance"], year: 2021, description: "Two teens prove ghosts and aliens are real through wild adventures." },
  { title: "Kaiju No. 8", category: "manga", genres: ["action", "sci-fi", "comedy", "shounen"], year: 2020, description: "A man gains the power to transform into a kaiju monster." },
  { title: "The Promised Neverland", category: "manga", genres: ["mystery", "thriller", "sci-fi", "dark fantasy", "shounen"], year: 2016, description: "Orphans discover a horrifying truth about their idyllic home." },
  { title: "Made in Abyss", category: "manga", genres: ["adventure", "dark fantasy", "mystery", "sci-fi"], year: 2012, description: "A girl descends into a mysterious abyss to find her mother." },
  { title: "Dorohedoro", category: "manga", genres: ["action", "comedy", "dark fantasy", "horror"], year: 2000, description: "A man with a reptile head seeks the sorcerer who cursed him." },
  { title: "Frieren: Beyond Journey's End", category: "manga", genres: ["adventure", "fantasy", "drama", "slice of life"], year: 2020, description: "An elf mage reflects on life after her heroic quest ended." },
  { title: "Solo Leveling", category: "manga", genres: ["action", "adventure", "fantasy", "shounen"], year: 2018, description: "The weakest hunter gains the power to level up without limits." },
  { title: "Tokyo Revengers", category: "manga", genres: ["action", "drama", "thriller", "sci-fi", "shounen"], year: 2017, description: "A man travels back in time to save his girlfriend by changing gang history." },
  { title: "Nana", category: "manga", genres: ["drama", "romance", "music", "slice of life", "shoujo"], year: 2000, description: "Two women named Nana form a powerful bond in Tokyo." },
  { title: "Fruits Basket", category: "manga", genres: ["romance", "comedy", "drama", "supernatural", "shoujo"], year: 1998, description: "A girl discovers a family cursed to transform into zodiac animals." },
  { title: "Ouran High School Host Club", category: "manga", genres: ["comedy", "romance", "shoujo", "slice of life"], year: 2002, description: "A scholarship student joins an elite school's charming host club." },
  { title: "Banana Fish", category: "manga", genres: ["action", "drama", "thriller", "crime"], year: 1985, description: "A gang leader and journalist unravel a drug conspiracy in NYC." },
  { title: "Akira", category: "manga", genres: ["action", "sci-fi", "cyberpunk", "thriller"], year: 1982, description: "A biker gang member gains psychic powers in post-apocalyptic Tokyo." },
  { title: "Claymore", category: "manga", genres: ["action", "dark fantasy", "adventure", "horror"], year: 2001, description: "Half-human female warriors hunt shape-shifting demons." },
  { title: "D.Gray-man", category: "manga", genres: ["action", "adventure", "dark fantasy", "shounen"], year: 2004, description: "An exorcist fights demonic weapons with a cursed arm." },
  { title: "Parasyte", category: "manga", genres: ["action", "horror", "sci-fi", "psychological"], year: 1988, description: "An alien parasite takes over a teen's right hand." },
  { title: "Gantz", category: "manga", genres: ["action", "horror", "sci-fi", "thriller"], year: 2000, description: "Dead people are forced to hunt aliens in a deadly game." },
  { title: "Kingdom", category: "manga", genres: ["action", "drama", "historical", "military"], year: 2006, description: "An orphan aims to become the greatest general in ancient China." },
  { title: "Kuroko's Basketball", category: "manga", genres: ["sports", "comedy", "shounen"], year: 2008, description: "An invisible-style player teams up with a powerful but raw talent." },
  { title: "Yotsuba&!", category: "manga", genres: ["comedy", "slice of life", "feel-good"], year: 2003, description: "An energetic little girl discovers the joys of everyday life." },
  { title: "A Silent Voice", category: "manga", genres: ["drama", "romance", "coming-of-age", "slice of life"], year: 2013, description: "A former bully seeks redemption by reconnecting with a deaf girl." },
  { title: "Blue Period", category: "manga", genres: ["drama", "coming-of-age", "slice of life", "art"], year: 2017, description: "A popular student discovers his passion for painting." },
  { title: "Oshi no Ko", category: "manga", genres: ["drama", "mystery", "supernatural", "music"], year: 2020, description: "A doctor is reborn as the child of his favorite pop idol." },
  { title: "Sakamoto Days", category: "manga", genres: ["action", "comedy", "shounen"], year: 2020, description: "A retired legendary hitman runs a convenience store." },
  { title: "Undead Unluck", category: "manga", genres: ["action", "comedy", "supernatural", "romance", "shounen"], year: 2020, description: "A girl cursed with bad luck pairs with an immortal man." },
  { title: "Witch Hat Atelier", category: "manga", genres: ["fantasy", "adventure", "mystery", "art"], year: 2016, description: "A girl discovers she can learn magic through drawing." },

  // ========================  BOOKS  ========================
  { title: "Harry Potter", category: "book", genres: ["fantasy", "adventure", "coming-of-age", "mystery"], year: 1997, description: "A boy discovers he's a wizard and attends a magical school." },
  { title: "The Lord of the Rings", category: "book", genres: ["fantasy", "adventure", "epic"], year: 1954, description: "A hobbit embarks on a quest to destroy an evil ring." },
  { title: "The Hunger Games", category: "book", genres: ["sci-fi", "dystopian", "action", "thriller", "young adult"], year: 2008, description: "A girl volunteers to fight to the death in a televised arena." },
  { title: "1984", category: "book", genres: ["sci-fi", "dystopian", "political", "thriller"], year: 1949, description: "A man rebels against a totalitarian regime that controls everything." },
  { title: "Pride and Prejudice", category: "book", genres: ["romance", "drama", "classic", "comedy"], year: 1813, description: "A witty woman and a proud man navigate love and class." },
  { title: "To Kill a Mockingbird", category: "book", genres: ["drama", "classic", "coming-of-age", "historical"], year: 1960, description: "A lawyer defends an innocent Black man in the racist South." },
  { title: "The Great Gatsby", category: "book", genres: ["drama", "classic", "romance", "tragedy"], year: 1925, description: "A mysterious millionaire throws lavish parties to win back his love." },
  { title: "Dune", category: "book", genres: ["sci-fi", "adventure", "political", "epic"], year: 1965, description: "A young noble navigates politics and prophecy on a desert planet." },
  { title: "The Hitchhiker's Guide to the Galaxy", category: "book", genres: ["sci-fi", "comedy", "adventure", "satire"], year: 1979, description: "An ordinary man is swept into a wild journey through space." },
  { title: "Ender's Game", category: "book", genres: ["sci-fi", "action", "military", "young adult"], year: 1985, description: "A child genius is trained to command humanity's fleet against aliens." },
  { title: "The Hobbit", category: "book", genres: ["fantasy", "adventure", "classic"], year: 1937, description: "A hobbit joins dwarves on a quest to reclaim a dragon's treasure." },
  { title: "A Game of Thrones", category: "book", genres: ["fantasy", "political", "drama", "epic", "dark fantasy"], year: 1996, description: "Noble families vie for control of a vast fantasy kingdom." },
  { title: "The Name of the Wind", category: "book", genres: ["fantasy", "adventure", "drama", "mystery"], year: 2007, description: "A legendary figure recounts his extraordinary life story." },
  { title: "Mistborn: The Final Empire", category: "book", genres: ["fantasy", "adventure", "action", "heist"], year: 2006, description: "A street thief discovers she has rare powers to overthrow a tyrant." },
  { title: "The Maze Runner", category: "book", genres: ["sci-fi", "dystopian", "action", "thriller", "young adult"], year: 2009, description: "A boy wakes up in a deadly maze with no memory." },
  { title: "Divergent", category: "book", genres: ["sci-fi", "dystopian", "action", "romance", "young adult"], year: 2011, description: "A girl discovers she doesn't fit into her society's rigid factions." },
  { title: "The Fault in Our Stars", category: "book", genres: ["romance", "drama", "young adult", "coming-of-age"], year: 2012, description: "Two teens with cancer fall in love." },
  { title: "Gone Girl", category: "book", genres: ["mystery", "thriller", "psychological", "drama"], year: 2012, description: "A woman disappears and suspicion falls on her husband." },
  { title: "The Girl with the Dragon Tattoo", category: "book", genres: ["mystery", "thriller", "crime", "drama"], year: 2005, description: "A journalist and hacker investigate a decades-old disappearance." },
  { title: "It", category: "book", genres: ["horror", "thriller", "coming-of-age", "supernatural"], year: 1986, description: "A group of kids confront a shape-shifting evil clown." },
  { title: "The Shining", category: "book", genres: ["horror", "thriller", "psychological", "supernatural"], year: 1977, description: "A family is terrorized by supernatural forces in an isolated hotel." },
  { title: "Project Hail Mary", category: "book", genres: ["sci-fi", "adventure", "comedy", "thriller"], year: 2021, description: "An amnesiac astronaut must save Earth from an extinction event." },
  { title: "The Martian", category: "book", genres: ["sci-fi", "adventure", "comedy", "thriller"], year: 2011, description: "An astronaut stranded on Mars must science his way to survival." },
  { title: "Brave New World", category: "book", genres: ["sci-fi", "dystopian", "classic", "political"], year: 1932, description: "A genetically engineered society trades freedom for stability." },
  { title: "Fahrenheit 451", category: "book", genres: ["sci-fi", "dystopian", "classic", "drama"], year: 1953, description: "A fireman whose job is to burn books begins to question everything." },
  { title: "The Catcher in the Rye", category: "book", genres: ["drama", "coming-of-age", "classic"], year: 1951, description: "A troubled teen wanders New York City after being expelled." },
  { title: "Percy Jackson & the Olympians", category: "book", genres: ["fantasy", "adventure", "comedy", "young adult", "mythology"], year: 2005, description: "A boy discovers he's the son of a Greek god." },
  { title: "Circe", category: "book", genres: ["fantasy", "mythology", "drama", "historical"], year: 2018, description: "The witch Circe carves out a life among gods and mortals." },
  { title: "The Song of Achilles", category: "book", genres: ["fantasy", "romance", "mythology", "drama", "historical"], year: 2011, description: "The love story of Achilles and Patroclus during the Trojan War." },
  { title: "Educated", category: "book", genres: ["memoir", "drama", "coming-of-age", "nonfiction"], year: 2018, description: "A woman escapes her survivalist family through education." },
  { title: "Sapiens", category: "book", genres: ["nonfiction", "history", "science", "political"], year: 2011, description: "A sweeping history of humankind from ancient to modern times." },
  { title: "Atomic Habits", category: "book", genres: ["nonfiction", "self-help", "psychology"], year: 2018, description: "Small changes in habits lead to remarkable results." },
  { title: "The Silent Patient", category: "book", genres: ["mystery", "thriller", "psychological"], year: 2019, description: "A woman shoots her husband and never speaks again." },
  { title: "Where the Crawdads Sing", category: "book", genres: ["mystery", "drama", "romance", "coming-of-age"], year: 2018, description: "An isolated marsh girl is suspected of murder." },
  { title: "Fourth Wing", category: "book", genres: ["fantasy", "romance", "action", "adventure"], year: 2023, description: "A young woman enters a brutal dragon-rider military academy." },
  { title: "House of Leaves", category: "book", genres: ["horror", "mystery", "psychological", "experimental"], year: 2000, description: "A family discovers their house is bigger on the inside." },
  { title: "The Poppy War", category: "book", genres: ["fantasy", "dark fantasy", "military", "historical"], year: 2018, description: "A war orphan discovers shamanic powers at a military academy." },
  { title: "Six of Crows", category: "book", genres: ["fantasy", "heist", "adventure", "young adult"], year: 2015, description: "A crew of outcasts attempts an impossible heist." },
  { title: "The Cruel Prince", category: "book", genres: ["fantasy", "romance", "young adult", "dark fantasy"], year: 2018, description: "A mortal girl navigates the dangerous faerie courts." },
  { title: "Red Rising", category: "book", genres: ["sci-fi", "action", "dystopian", "epic"], year: 2014, description: "A miner infiltrates the ruling class of a color-coded society on Mars." },
  { title: "The Way of Kings", category: "book", genres: ["fantasy", "epic", "adventure", "military"], year: 2010, description: "Warriors and scholars face an ancient return of devastating storms." },
  { title: "Children of Time", category: "book", genres: ["sci-fi", "adventure", "thriller"], year: 2015, description: "Humanity's last survivors encounter an evolved spider civilization." },
  { title: "The Handmaid's Tale", category: "book", genres: ["sci-fi", "dystopian", "drama", "political"], year: 1985, description: "A woman struggles for survival in a theocratic dictatorship." },
  { title: "Normal People", category: "book", genres: ["romance", "drama", "coming-of-age", "slice of life"], year: 2018, description: "Two Irish teens navigate love and class through college." },
  { title: "The Seven Husbands of Evelyn Hugo", category: "book", genres: ["romance", "drama", "historical", "mystery"], year: 2017, description: "A glamorous old Hollywood star reveals her scandalous life story." },
  { title: "A Court of Thorns and Roses", category: "book", genres: ["fantasy", "romance", "adventure", "young adult"], year: 2015, description: "A huntress is dragged into a magical faerie land." },
  { title: "Piranesi", category: "book", genres: ["fantasy", "mystery", "philosophical"], year: 2020, description: "A man lives in a labyrinthine house filled with ocean tides and statues." },
  { title: "Mexican Gothic", category: "book", genres: ["horror", "mystery", "gothic", "historical"], year: 2020, description: "A socialite investigates her cousin's mysterious illness in a creepy mansion." },
  { title: "Klara and the Sun", category: "book", genres: ["sci-fi", "drama", "philosophical"], year: 2021, description: "An AI companion observes the human world from a store window." },
  { title: "The Invisible Life of Addie LaRue", category: "book", genres: ["fantasy", "romance", "historical", "drama"], year: 2020, description: "A woman cursed to be forgotten meets someone who remembers her." },
  { title: "Babel", category: "book", genres: ["fantasy", "historical", "dark fantasy", "political"], year: 2022, description: "A student at Oxford discovers the dark power behind translation magic." },
  { title: "Tomorrow, and Tomorrow, and Tomorrow", category: "book", genres: ["drama", "romance", "coming-of-age"], year: 2022, description: "Two friends create video games over three decades." },
  { title: "Legends & Lattes", category: "book", genres: ["fantasy", "slice of life", "feel-good", "romance"], year: 2022, description: "A retired barbarian opens a coffee shop in a fantasy world." },
  { title: "The House in the Cerulean Sea", category: "book", genres: ["fantasy", "feel-good", "romance", "comedy"], year: 2020, description: "A caseworker visits an orphanage for magical children." },

  // ========================  TV SHOWS  ========================
  { title: "Breaking Bad", category: "tv", genres: ["drama", "crime", "thriller"], year: 2008, description: "A chemistry teacher turns to making meth after a cancer diagnosis." },
  { title: "Game of Thrones", category: "tv", genres: ["fantasy", "drama", "political", "epic", "dark fantasy"], year: 2011, description: "Noble families battle for control of a mythical kingdom." },
  { title: "Stranger Things", category: "tv", genres: ["sci-fi", "horror", "drama", "mystery", "coming-of-age"], year: 2016, description: "Kids in a small town encounter supernatural forces from another dimension." },
  { title: "The Office", category: "tv", genres: ["comedy", "mockumentary", "slice of life"], year: 2005, description: "The daily lives of office employees at a paper company." },
  { title: "Friends", category: "tv", genres: ["comedy", "romance", "slice of life"], year: 1994, description: "Six friends navigate life and love in New York City." },
  { title: "The Last of Us", category: "tv", genres: ["drama", "action", "horror", "sci-fi", "post-apocalyptic"], year: 2023, description: "A smuggler escorts a girl across a fungal-infected America." },
  { title: "Wednesday", category: "tv", genres: ["comedy", "mystery", "supernatural", "coming-of-age", "horror"], year: 2022, description: "Wednesday Addams solves mysteries at a school for outcasts." },
  { title: "Squid Game", category: "tv", genres: ["thriller", "drama", "action", "dystopian"], year: 2021, description: "Desperate people play deadly children's games for a cash prize." },
  { title: "The Mandalorian", category: "tv", genres: ["sci-fi", "action", "adventure", "western"], year: 2019, description: "A lone bounty hunter protects a mysterious alien child." },
  { title: "The Witcher", category: "tv", genres: ["fantasy", "action", "adventure", "drama"], year: 2019, description: "A monster hunter navigates a world of magic and political intrigue." },
  { title: "Arcane", category: "tv", genres: ["action", "adventure", "fantasy", "drama", "sci-fi", "steampunk"], year: 2021, description: "Two sisters clash in a city divided by technology and magic." },
  { title: "Ted Lasso", category: "tv", genres: ["comedy", "sports", "drama", "feel-good"], year: 2020, description: "An optimistic American coach takes over a struggling English football team." },
  { title: "The Bear", category: "tv", genres: ["drama", "comedy", "slice of life"], year: 2022, description: "A chef returns home to run his late brother's sandwich shop." },
  { title: "Succession", category: "tv", genres: ["drama", "political", "comedy", "thriller"], year: 2018, description: "Siblings compete for control of a media empire." },
  { title: "True Detective", category: "tv", genres: ["crime", "drama", "mystery", "thriller"], year: 2014, description: "Detectives investigate dark crimes across different timelines." },
  { title: "Sherlock", category: "tv", genres: ["mystery", "crime", "drama", "thriller"], year: 2010, description: "A modern-day Sherlock Holmes solves cases in London." },
  { title: "Dark", category: "tv", genres: ["sci-fi", "mystery", "thriller", "drama"], year: 2017, description: "A child's disappearance exposes a time-travel conspiracy across generations." },
  { title: "Black Mirror", category: "tv", genres: ["sci-fi", "thriller", "dystopian", "psychological", "drama"], year: 2011, description: "Standalone stories explore the dark side of technology." },
  { title: "The Boys", category: "tv", genres: ["action", "superhero", "comedy", "thriller", "drama"], year: 2019, description: "Vigilantes fight corrupt superheroes who abuse their power." },
  { title: "Invincible", category: "tv", genres: ["action", "superhero", "drama", "thriller"], year: 2021, description: "A teen inherits his father's superpowers and discovers dark secrets." },
  { title: "Peaky Blinders", category: "tv", genres: ["crime", "drama", "historical", "thriller"], year: 2013, description: "A gangster family rises to power in post-WWI Birmingham." },
  { title: "Money Heist", category: "tv", genres: ["crime", "thriller", "action", "drama", "heist"], year: 2017, description: "A criminal mastermind leads the biggest heist in history." },
  { title: "The Crown", category: "tv", genres: ["drama", "historical", "political"], year: 2016, description: "The reign of Queen Elizabeth II across decades." },
  { title: "Fleabag", category: "tv", genres: ["comedy", "drama", "romance"], year: 2016, description: "A witty, troubled woman navigates life and love in London." },
  { title: "Abbott Elementary", category: "tv", genres: ["comedy", "mockumentary", "slice of life", "feel-good"], year: 2021, description: "Teachers navigate a chronically underfunded public school." },
  { title: "Severance", category: "tv", genres: ["sci-fi", "thriller", "mystery", "psychological", "drama"], year: 2022, description: "Workers undergo a procedure to separate work and personal memories." },
  { title: "Yellowjackets", category: "tv", genres: ["thriller", "mystery", "horror", "drama"], year: 2021, description: "A girls' soccer team survives a plane crash and its dark aftermath." },
  { title: "House of the Dragon", category: "tv", genres: ["fantasy", "drama", "political", "epic", "dark fantasy"], year: 2022, description: "The Targaryen civil war tears a dragon-riding dynasty apart." },
  { title: "Shogun", category: "tv", genres: ["drama", "historical", "political", "action", "adventure"], year: 2024, description: "An English sailor becomes entangled in feudal Japan's power struggles." },
  { title: "Fallout", category: "tv", genres: ["sci-fi", "action", "adventure", "comedy", "post-apocalyptic"], year: 2024, description: "Survivors navigate the irradiated wasteland of post-nuclear America." },
  { title: "The Penguin", category: "tv", genres: ["crime", "drama", "thriller", "action"], year: 2024, description: "Oz Cobb rises through Gotham's criminal underworld." },
  { title: "Beef", category: "tv", genres: ["comedy", "drama", "thriller", "psychological"], year: 2023, description: "A road rage incident spirals into an all-consuming feud." },
  { title: "Reacher", category: "tv", genres: ["action", "crime", "thriller", "mystery"], year: 2022, description: "An ex-military investigator uncovers conspiracies in small-town America." },
  { title: "Only Murders in the Building", category: "tv", genres: ["comedy", "mystery", "crime"], year: 2021, description: "Three neighbors start a true-crime podcast about a murder in their building." },
  { title: "The Diplomat", category: "tv", genres: ["drama", "political", "thriller"], year: 2023, description: "A career diplomat is thrust into a high-stakes ambassador role in London." },
  { title: "Andor", category: "tv", genres: ["sci-fi", "drama", "thriller", "political"], year: 2022, description: "A thief becomes a rebel spy in the early days of the Rebellion." },
  { title: "The White Lotus", category: "tv", genres: ["drama", "comedy", "mystery", "satire"], year: 2021, description: "Wealthy guests unravel at a tropical resort." },
  { title: "Daisy Jones & The Six", category: "tv", genres: ["drama", "music", "romance"], year: 2023, description: "A fictional rock band rises and falls in the 1970s." },
  { title: "Blue Eye Samurai", category: "tv", genres: ["action", "adventure", "drama", "historical"], year: 2023, description: "A mixed-race swordsmith seeks revenge in Edo-period Japan." },
  { title: "Slow Horses", category: "tv", genres: ["thriller", "drama", "crime", "political"], year: 2022, description: "Disgraced MI5 agents stumble into real espionage cases." },
  { title: "The Gilded Age", category: "tv", genres: ["drama", "historical", "romance"], year: 2022, description: "Old money and new money clash in 1880s New York." },
  { title: "Heartstopper", category: "tv", genres: ["romance", "drama", "coming-of-age", "feel-good"], year: 2022, description: "Two schoolboys discover their unlikely friendship is something more." },
  { title: "Shadow and Bone", category: "tv", genres: ["fantasy", "adventure", "drama", "romance"], year: 2021, description: "An orphan soldier discovers a power that could free her war-torn country." },
  { title: "Loki", category: "tv", genres: ["sci-fi", "action", "adventure", "comedy", "superhero"], year: 2021, description: "The God of Mischief navigates the multiverse and time itself." },
  { title: "Silo", category: "tv", genres: ["sci-fi", "mystery", "thriller", "dystopian"], year: 2023, description: "People live in a massive underground silo where the truth is buried." },
  { title: "Lessons in Chemistry", category: "tv", genres: ["drama", "comedy", "historical"], year: 2023, description: "A 1960s female chemist becomes an unlikely TV cooking show star." },

  // ========================  MOVIES  ========================
  { title: "The Shawshank Redemption", category: "movie", genres: ["drama", "crime"], year: 1994, description: "A banker wrongly imprisoned finds hope and friendship behind bars." },
  { title: "The Dark Knight", category: "movie", genres: ["action", "superhero", "crime", "thriller", "drama"], year: 2008, description: "Batman faces the anarchic Joker in a battle for Gotham's soul." },
  { title: "Inception", category: "movie", genres: ["sci-fi", "action", "thriller", "psychological"], year: 2010, description: "A thief enters people's dreams to plant an idea." },
  { title: "Interstellar", category: "movie", genres: ["sci-fi", "adventure", "drama"], year: 2014, description: "Astronauts travel through a wormhole to save humanity." },
  { title: "Pulp Fiction", category: "movie", genres: ["crime", "drama", "comedy", "thriller"], year: 1994, description: "Interconnected stories of criminals in Los Angeles." },
  { title: "The Lord of the Rings: The Fellowship of the Ring", category: "movie", genres: ["fantasy", "adventure", "epic", "action"], year: 2001, description: "A hobbit begins a perilous journey to destroy an evil ring." },
  { title: "Spider-Man: Into the Spider-Verse", category: "movie", genres: ["action", "superhero", "comedy", "animation"], year: 2018, description: "A teen discovers multiple Spider-People from parallel dimensions." },
  { title: "Spirited Away", category: "movie", genres: ["fantasy", "adventure", "animation", "coming-of-age", "drama"], year: 2001, description: "A girl navigates a mystical spirit world to save her parents." },
  { title: "Your Name", category: "movie", genres: ["romance", "fantasy", "drama", "animation"], year: 2016, description: "Two strangers mysteriously swap bodies across time and space." },
  { title: "Parasite", category: "movie", genres: ["thriller", "drama", "comedy", "psychological"], year: 2019, description: "A poor family infiltrates a wealthy household with dark results." },
  { title: "Everything Everywhere All at Once", category: "movie", genres: ["action", "comedy", "sci-fi", "adventure", "drama"], year: 2022, description: "A laundromat owner discovers she can access multiverse versions of herself." },
  { title: "The Matrix", category: "movie", genres: ["sci-fi", "action", "thriller", "cyberpunk"], year: 1999, description: "A hacker discovers reality is a simulation controlled by machines." },
  { title: "Fight Club", category: "movie", genres: ["drama", "thriller", "psychological", "action"], year: 1999, description: "An insomniac forms an underground fight club." },
  { title: "Get Out", category: "movie", genres: ["horror", "thriller", "mystery", "psychological"], year: 2017, description: "A man uncovers disturbing secrets at his girlfriend's family estate." },
  { title: "The Silence of the Lambs", category: "movie", genres: ["thriller", "crime", "horror", "psychological"], year: 1991, description: "An FBI trainee seeks a cannibal's help to catch a serial killer." },
  { title: "Whiplash", category: "movie", genres: ["drama", "music", "thriller", "psychological"], year: 2014, description: "A drumming student is pushed to extremes by a ruthless instructor." },
  { title: "La La Land", category: "movie", genres: ["romance", "drama", "music", "comedy"], year: 2016, description: "An aspiring actress and jazz musician chase dreams in LA." },
  { title: "The Grand Budapest Hotel", category: "movie", genres: ["comedy", "adventure", "crime", "drama"], year: 2014, description: "A hotel concierge and his protégé get caught up in art theft." },
  { title: "Mad Max: Fury Road", category: "movie", genres: ["action", "adventure", "sci-fi", "post-apocalyptic", "thriller"], year: 2015, description: "A warrior and a drifter flee across a post-apocalyptic wasteland." },
  { title: "Dune (2021)", category: "movie", genres: ["sci-fi", "adventure", "epic", "action", "drama"], year: 2021, description: "A young noble must navigate the dangers of the desert planet Arrakis." },
  { title: "Oppenheimer", category: "movie", genres: ["drama", "historical", "thriller", "political"], year: 2023, description: "The story of the physicist who helped build the atomic bomb." },
  { title: "Barbie", category: "movie", genres: ["comedy", "fantasy", "adventure", "satire"], year: 2023, description: "Barbie ventures into the real world and questions her existence." },
  { title: "John Wick", category: "movie", genres: ["action", "thriller", "crime"], year: 2014, description: "A retired hitman goes on a rampage after his dog is killed." },
  { title: "The Social Network", category: "movie", genres: ["drama", "thriller", "historical"], year: 2010, description: "The founding of Facebook and the lawsuits that followed." },
  { title: "Arrival", category: "movie", genres: ["sci-fi", "drama", "mystery", "thriller"], year: 2016, description: "A linguist attempts to communicate with visiting aliens." },
  { title: "Blade Runner 2049", category: "movie", genres: ["sci-fi", "drama", "mystery", "thriller", "cyberpunk"], year: 2017, description: "A replicant officer unearths a secret that could destabilize society." },
  { title: "The Truman Show", category: "movie", genres: ["drama", "comedy", "sci-fi", "psychological"], year: 1998, description: "A man discovers his entire life is a TV show." },
  { title: "Eternal Sunshine of the Spotless Mind", category: "movie", genres: ["romance", "drama", "sci-fi", "psychological"], year: 2004, description: "An estranged couple undergoes a procedure to erase each other from memory." },
  { title: "Howl's Moving Castle", category: "movie", genres: ["fantasy", "romance", "adventure", "animation"], year: 2004, description: "A cursed girl finds refuge in a wizard's magical moving castle." },
  { title: "Princess Mononoke", category: "movie", genres: ["fantasy", "adventure", "action", "drama", "animation"], year: 1997, description: "A warrior is caught between forest gods and mining colonists." },
  { title: "Knives Out", category: "movie", genres: ["mystery", "comedy", "crime", "thriller"], year: 2019, description: "A detective investigates the death of a wealthy mystery author." },
  { title: "The Batman", category: "movie", genres: ["action", "superhero", "crime", "mystery", "thriller"], year: 2022, description: "Batman hunts a sadistic serial killer targeting Gotham's elite." },
  { title: "Top Gun: Maverick", category: "movie", genres: ["action", "adventure", "drama"], year: 2022, description: "An aging pilot trains a new generation for a dangerous mission." },
  { title: "Coco", category: "movie", genres: ["adventure", "comedy", "fantasy", "animation", "music", "coming-of-age"], year: 2017, description: "A boy enters the Land of the Dead to find his musician ancestor." },
  { title: "Inside Out", category: "movie", genres: ["comedy", "drama", "animation", "coming-of-age", "fantasy"], year: 2015, description: "Emotions inside a girl's mind navigate her move to a new city." },
  { title: "Hereditary", category: "movie", genres: ["horror", "thriller", "psychological", "supernatural"], year: 2018, description: "A family is haunted by a sinister presence after a death." },
  { title: "Midsommar", category: "movie", genres: ["horror", "thriller", "psychological", "drama"], year: 2019, description: "A group attends a rural Swedish festival that turns sinister." },
  { title: "Poor Things", category: "movie", genres: ["comedy", "drama", "sci-fi", "romance"], year: 2023, description: "A resurrected woman explores the world with childlike wonder." },
  { title: "Past Lives", category: "movie", genres: ["romance", "drama"], year: 2023, description: "Childhood sweethearts reconnect decades later in New York." },
  { title: "The Menu", category: "movie", genres: ["thriller", "comedy", "horror"], year: 2022, description: "Wealthy diners attend an exclusive meal with a shocking twist." },
  { title: "Suzume", category: "movie", genres: ["fantasy", "adventure", "romance", "animation", "drama"], year: 2022, description: "A girl must close supernatural doors across Japan to prevent disasters." },
  { title: "The Boy and the Heron", category: "movie", genres: ["fantasy", "adventure", "drama", "animation"], year: 2023, description: "A boy enters a fantastical world guided by a mysterious heron." },
  { title: "Killers of the Flower Moon", category: "movie", genres: ["drama", "crime", "historical", "thriller"], year: 2023, description: "FBI investigates murders of Osage Nation members in 1920s Oklahoma." },
  { title: "Saltburn", category: "movie", genres: ["thriller", "drama", "psychological", "dark comedy"], year: 2023, description: "A student becomes dangerously obsessed with his wealthy classmate." },
  { title: "Wonka", category: "movie", genres: ["comedy", "fantasy", "adventure", "feel-good"], year: 2023, description: "A young Willy Wonka discovers his dream of opening a chocolate shop." },
  { title: "Dune: Part Two", category: "movie", genres: ["sci-fi", "adventure", "epic", "action", "drama"], year: 2024, description: "Paul Atreides unites with the Fremen to take on House Harkonnen." },
  { title: "Inside Out 2", category: "movie", genres: ["comedy", "drama", "animation", "coming-of-age"], year: 2024, description: "Riley hits puberty and new emotions join the party." },
  { title: "Furiosa: A Mad Max Saga", category: "movie", genres: ["action", "adventure", "sci-fi", "post-apocalyptic"], year: 2024, description: "The origin story of the warrior Furiosa in the wasteland." },
  { title: "The Wild Robot", category: "movie", genres: ["adventure", "animation", "sci-fi", "drama", "feel-good"], year: 2024, description: "A robot learns to survive and nurture life on a wild island." },
  { title: "Alien: Romulus", category: "movie", genres: ["horror", "sci-fi", "thriller", "action"], year: 2024, description: "Young space colonists face a terrifying xenomorph threat." },
  { title: "Challengers", category: "movie", genres: ["drama", "romance", "sports", "thriller"], year: 2024, description: "A love triangle plays out through the world of professional tennis." },
  { title: "Civil War", category: "movie", genres: ["action", "drama", "thriller", "political"], year: 2024, description: "Journalists navigate a near-future American civil war." },
  { title: "A Quiet Place: Day One", category: "movie", genres: ["horror", "thriller", "sci-fi", "drama"], year: 2024, description: "The alien invasion begins in the streets of New York City." },
  { title: "Wicked", category: "movie", genres: ["fantasy", "musical", "drama", "adventure"], year: 2024, description: "Two witches form an unlikely friendship at a magical university." },
  { title: "Gladiator II", category: "movie", genres: ["action", "drama", "historical", "epic"], year: 2024, description: "A man with a grudge against Rome enters the gladiatorial arena." },
  { title: "The Substance", category: "movie", genres: ["horror", "sci-fi", "thriller", "drama"], year: 2024, description: "A fading celebrity uses a mysterious drug to create a younger self." },
];

// Make available globally
if (typeof module !== 'undefined' && module.exports) {
  module.exports = DATABASE;
}
